-- MySQL Script generated by MySQL Workbench
-- Mon Nov 30 13:15:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Klient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Klient` (
  `idKlient` INT NOT NULL,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Wiek` INT NULL,
  `NrTel` INT NULL,
  `Email` VARCHAR(45) NULL,
  `RodzajUlgi` VARCHAR(45) NULL,
  PRIMARY KEY (`idKlient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Przystanek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Przystanek` (
  `idPrzystanek` INT NOT NULL,
  `Nazwa` VARCHAR(45) NULL,
  PRIMARY KEY (`idPrzystanek`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trasa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trasa` (
  `idTrasa` INT NOT NULL,
  `czas` DATETIME NULL,
  `idPrzystanek` INT NULL,
  PRIMARY KEY (`idTrasa`),
  INDEX `idPrzystanek_idx` (`idPrzystanek` ASC) VISIBLE,
  CONSTRAINT `idPrzystanek`
    FOREIGN KEY (`idPrzystanek`)
    REFERENCES `mydb`.`Przystanek` (`idPrzystanek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kurs` (
  `idKurs` INT NOT NULL,
  `Przewoznik` VARCHAR(45) NULL,
  `ilosc_miejsc` INT NULL,
  `Cena` DOUBLE NULL,
  `idTrasa` INT NULL,
  PRIMARY KEY (`idKurs`),
  INDEX `idTrasa_idx` (`idTrasa` ASC) VISIBLE,
  CONSTRAINT `idTrasa`
    FOREIGN KEY (`idTrasa`)
    REFERENCES `mydb`.`Trasa` (`idTrasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KupioneBilety`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KupioneBilety` (
  `idBilet` INT NOT NULL,
  `idKlient` INT NULL,
  `idKurs` INT NULL,
  PRIMARY KEY (`idBilet`),
  INDEX `idKurs_idx` (`idKurs` ASC) VISIBLE,
  INDEX `idKlient_idx` (`idKlient` ASC) VISIBLE,
  CONSTRAINT `idKlient`
    FOREIGN KEY (`idKlient`)
    REFERENCES `mydb`.`Klient` (`idKlient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idKurs`
    FOREIGN KEY (`idKurs`)
    REFERENCES `mydb`.`Kurs` (`idKurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
